from frames.acts import Acts
from frames.allevents import AllEvents
from frames.craigsgraphs import GraphsCraigs
from frames.demographics import Demographics
from frames.housing import Housing
from frames.map import Map
from frames.startpage import StartPage
from frames.vaccine import Vaccine
from frames.weather import Weather
